### ISSUE TITLE
Is the model trained on pre-trained SD3 or from scratch?

### ISSUE THREAD

**Issue by volcverse** [DerrickWang005/LaVin-DiT#1]
Hi, thanks for the great work!

Could you please tell me that if the model is trained on pre-trained SD3 or from scratch? I'm curious about this.

**Comment by DerrickWang005** [comment]
We train all models from scratch. Our model is different with SD3. So, We cannot initialize via SD3's weights.

**Comment by volcverse** [comment]
Thank you for your timely response! 
Looking forward to the code being open-sourced! :)
